config/routes.rb
Rails.application.routes.draw do

  resources :comments

  resource :posts

  resource :relationships, only: [:create, :destroy]

  resource :users, only: [:edit, :update] do
    member	do
      get :wish_frend, :del_wish_frend
      get :accept_frend, :not_accept_frend
    end
  end

  match 'post/id',  to: 'posts#show_id',    via: 'get', as: :post_show_id

  match 'likes',  to: 'likes#add_delete',    via: 'get', as: :likes_add_delete

  match 'users/show_new_friends',  to: 'users#show_new_friends',    via: 'get' , as: :show_users_new_friends
  match 'users/show_invites',  to: 'users#show_invites',    via: 'get' , as: :show_users_invites
  match 'users/show_wishes',  to: 'users#show_wishes',    via: 'get' , as: :show_users_wishes
  match 'users/show_friends',  to: 'users#show_friends',    via: 'get' , as: :show_users_friends

  match 'users/:id/show',  to: 'users#show',    via: 'get' , as: :show_users
  match 'users/index',  to: 'users#index',     via: 'get'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable


  devise :omniauthable, :omniauth_providers => [:facebook]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { medium: "150x150#", thumb: '80x80>' },
                                  :default_url => "/images/default_image.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/


  has_many :wish_frends, through: :relationships, source: :inv
  has_many :relationships, foreign_key: "wish_id", dependent:			:destroy

  has_many :inv_frends, through:	:reverse_relationships,	source:	:wish
  has_many	:reverse_relationships,	foreign_key: "inv_id",
                      class_name: "Relationship",  dependent:			:destroy

  has_many :posts

  has_many :likes
  has_many :posts_likes, through: :likes, source: :post

  has_many :comments

  def accept_inv(user)
    relation = self.reverse_relationships.find_by(wish_id: user.id)
    relation.accepted = true
    relation.save
  end

  def seen_friend(user)
    relation = self.relationships.find_by(inv_id: user.id)
    relation.seen = true
    relation.save
  end

  def delete_inv(user)
    self.inv_frends.delete(user.id)
  end

  def delete_wish(user)
    self.wish_frends.delete(user.id)
  end

  def delete_realtionship(user)
    delete_wish(user) if self.wish_frends.any?{|u| u == user }
    delete_inv(user) if self.inv_frends.any?{|u| u == user }
  end

  def frends
    friendships = "SELECT wish_id FROM relationships WHERE inv_id = :user_id
						AND accepted = true"
    reverse_friendships = "SELECT inv_id FROM relationships WHERE wish_id = :user_id
        		AND accepted = true"
    User.where("id IN (#{friendships}) OR id IN (#{reverse_friendships})", user_id: self.id)
  end

  def current_wishes
    wishes = "SELECT inv_id FROM relationships WHERE wish_id = :user_id
            AND accepted = false"
    User.where("id IN (#{wishes})", user_id: self.id )
  end

  def current_invites
    inventes = "SELECT wish_id FROM relationships WHERE  inv_id = :user_id
            AND accepted = false"
    User.where("id IN (#{inventes})", user_id: self.id )
  end

  def new_friends
    reverse_friendships = "SELECT inv_id FROM relationships WHERE wish_id = :user_id
            AND accepted = true AND seen = false"
    User.where("id IN (#{reverse_friendships})", user_id: self.id)
  end

  def relationship?(user)
    return :wish if self.current_wishes.any?{|u| u == user }
    return :invit if self.current_invites.any?{|u| u == user }
    return :frend if self.frends.any?{|u| u == user }
    return nil
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.name   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
    end
  end



end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
  # You need to implement the method below in your model (e.g. app/models/user.rb)
    #puts "---------------env[omniath.auth] #{request.env["omniauth.auth"]} -----"
    @user = User.from_omniauth(request.env["omniauth.auth"])


    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end


  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :gender,
        :birthday, :location, :avatar )
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_log_in
  before_action :correct_user,   only: [:edit, :update]

  def index
    @users = User.all
  end




  def show_new_friends
    @users = current_user.new_friends
    @users.map{|user| current_user.seen_friend(user) }
    render 'index'
  end

  def show_friends
    @users = current_user.frends
    render 'index'
  end

  def show_invites
    @users = current_user.current_invites
    render 'index'
  end

  def show_wishes
    @users = current_user.current_wishes
    render 'index'
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
    @user = User.find(params[:format])
  end

  def update
    @user = User.find(params[:format])
    if  @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to root_path
    else
      flash[:danger] = 'Invalid old password' if !@user.authenticate(params[:user][:old_password])
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :gender,
        :birthday, :location, :avatar )
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_accept_friend.html.erb
<%=	form_for(current_user.relationships.
         build(inv_id:	@user.id))	do	|f|	%>
 <div>
 <%=	hidden_field_tag	:wish_id,	@user.id	%>
 <%=	hidden_field_tag	:accept,	true	%>
 </div>
 <%=	f.submit	@label,	class:	"btn	btn-success"	%>
<% end %>

app/views/users/_add_friend.html.erb
<%=	form_for(current_user.relationships.
         build(inv_id:	@user.id))	do	|f|	%>
 <div><%=	hidden_field_tag	:wish_id,	@user.id	%></div>
 <%=	f.submit	@label,	class:	"btn	btn-primary"	%>
<% end %>

app/views/users/_delete_relationship.html.erb
<%=	form_for(current_user.relationships.build(inv_id:	@user.id),
						 	            html:	{	method:	:delete	})	do	|f|	%>
	 <div><%=	hidden_field_tag	:wish_id,	@user.id	%></div>
		<%=	f.submit	@label,	class:	"btn	btn-warning"	%>
<%	end	%>

app/views/users/_relationship_form.html.erb
<% if current_user != @user %>
<div	id="relationship_form">
  <% @relationship = current_user.relationship?(@user) %>
  <% if @relationship == nil %>
   <% @label = "invite friend"  %>
   <%=	render	'add_friend'	%>
   <% else %>
   <% if @relationship == :invit %>
   <div>
     <% @label = "accept friend"  %>
     <div><%=	render	'accept_friend'	%></div>
     <% @label = "deny friend"  %><br>
     <div><%=	render	'delete_relationship'	%></div>
   </div>
   <% end %>
   <% if @relationship == :frend %>
     <% @label = "deny friend"  %>
     <%=	render	'delete_relationship'	%>
   <% end %>
   <% if @relationship == :wish %>
     <% @label = "deny my wish to be frend"  %>
     <%=	render	'delete_relationship'	%>
   <% end %>
 <% end %>
</div>
<% end %>

app/views/users/edit.html.erb
<div style = "text-align : left; margin: 20px;">
<%= devise_error_messages! %>
<h1>Edit Profile</h1>

<%= image_tag @user.avatar.url(:medium) %>

<%= form_for(@user, url: users_path ) do |f| %>

<%= hidden_field_tag :format, @user.id %>

<%= f.file_field :avatar %>


  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, autofocus: true,
                                          class: "signin-field",  value: @user.first_name %>
    <br>
    <%= f.label :Last_name %>
    <br>
    <%= f.text_field :last_name, autofocus: true,
                                          class: " signin-field",  value: @user.last_name  %>
  </div>

  <br>
  <%= f.label :gender %>
  <%= f.select :gender, options_for_select(["Male", "Female"]), value: @user.gender  %><br/>

  <br>
  <%= f.label :birthday %>
	<%= f.date_select :birthday, start_year: 1910 %><br/>
  <br>

  <br>
  <%= f.label :location %>
  <br>
  <%= f.text_field :location, autofocus: true,
                                        class: " signin-field", value:  @user.location %>

  <br>
  <br>
  <%= f.submit "Update" %>

<% end %>
</div>

app/views/users/index.html.erb
<div style = "text-align : left; margin: 20px;">

  <% @users.each do |user| %>
  <br>
<div>
     <%= image_tag user.avatar.url(:thumb) %>
      <%= link_to "#{user.first_name} #{user.last_name}" , show_users_path(user) %>
      <%= user.email %>
      <% @user = user %>
      <%= render 'users/relationship_form'  %>

</div>

      <br>
  <% end %>

</div>

app/views/users/show.html.erb
<h2><%= "#{@user.first_name} #{@user.last_name}" %></h2>
<br>
<br>
<%= image_tag @user.avatar.url(:medium) %>
<br>

 <br>
 <%= @user.email %>
 <br>
 <br>
 <p><b>Gender: </b><%= current_user.gender %></p>
 <p><b>Location:</b> <%= current_user.location %></p>
 <p><b>Birthdate:</b> <%= current_user.birthday %></p>
 <%=	render	'relationship_form'	%>
<br>

<div>
  <%= render 'posts/list_post', posts: @user.posts %>
</div>