config/routes.rb
Rails.application.routes.draw do

  resources :comments

  resource :posts

  resource :relationships, only: [:create, :destroy]

  resource :users, only: [:edit, :update] do
    member	do
      get :wish_frend, :del_wish_frend
      get :accept_frend, :not_accept_frend
    end
  end

  match 'post/id',  to: 'posts#show_id',    via: 'get', as: :post_show_id

  match 'likes',  to: 'likes#add_delete',    via: 'get', as: :likes_add_delete

  match 'users/show_new_friends',  to: 'users#show_new_friends',    via: 'get' , as: :show_users_new_friends
  match 'users/show_invites',  to: 'users#show_invites',    via: 'get' , as: :show_users_invites
  match 'users/show_wishes',  to: 'users#show_wishes',    via: 'get' , as: :show_users_wishes
  match 'users/show_friends',  to: 'users#show_friends',    via: 'get' , as: :show_users_friends

  match 'users/:id/show',  to: 'users#show',    via: 'get' , as: :show_users
  match 'users/index',  to: 'users#index',     via: 'get'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'welcome#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :title, presence: true, length: { maximum: 140 }
  validates :content, presence: true
  validates :user_id, presence: true

  has_many :likes
  has_many :users_likes, through: :likes, source: :user

  has_many :comments
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


    def show_id
      @posts = []
      @posts << Post.find(params[:format])
      render '_posts'
    end

    def show
      friends = current_user.frends
      friends = friends << current_user
      sql = ""
      friends.each do |user|
        sql = sql + "user_id = #{user.id} OR "
      end
      @posts = Post.where(sql[0..-5])

    end

    def create
      @post = current_user.posts.build(post_params)
      @post.date = Time.now
      @post.save
      redirect_to root_path
    end

    def destroy
      if current_user.posts.find_by(id: params[:format])
        current_user.posts.find_by(id: params[:format]).destroy
        flash[:success] = "Micropost deleted"
        redirect_to  root_url
      else
        flash[:danger] = "You can't delete this post"
        redirect_to  root_url
      end
    end

    def edit
      if current_user.posts.find_by(id: params[:format])
        @post = current_user.posts.find_by(id: params[:format])
      else
        flash[:danger] = "You can't edit this post"
        redirect_to  root_url
      end
    end

    def update
      id = params[:post][:id].to_s
      if current_user.posts.find_by(id: id).update_attributes(post_params)
          flash[:success] = "Post updated"
          redirect_to  root_url
      else
        flash[:danger] = "You can't edit this post"
        redirect_to  root_url
      end
    end

private

  def post_params
    params.require(:post).permit(:id, :title, :content)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comments.html.erb
<h5 class="form-comment">Comments </h5>
<% post.comments.each do |comment| %>
<div style = "text-align: left; margin-left: 200px;">
  <%= link_to "#{comment.user.first_name}: ", show_users_path(comment.user) %>
  <%= comment.content %>
</div>
<% end %>

<br>
<%= form_for( Comment.new) do |f| %>
  <div class="field form-comment">
    <%= f.label current_user.first_name , id: "form-comment" %>
    <%= f.text_field :content , size: "60x", placeholder: "Compose you comment..." %><br>
    <%= hidden_field_tag :post_id, post.id %>
    <%= f.submit "Puts your comment.. ", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/posts/_form_post.html.erb
<%= form_for(@post) do |f| %>

  <div class="field">

    <%= f.label "Title"  %><br>
    <%= f.text_field :title , size: "60x" %><br><br>
    <%= f.text_area :content, size: "60x12", placeholder: "Compose new post..." %><br>
  </div>
<%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/posts/_list_post.html.erb
<ul style = "text-align: left; margin: 10px 100px 10px 300px">
<h3> Posts </h3>
<%  posts.each do |post| %>
  <li> <%= link_to post.title, post_show_id_path(post.id) %> </li>
<% end %>
</ul>

app/views/posts/_posts.html.erb
<h3> Posts </h3>
<%  @posts.each do |post| %>
<div style = "width:300p; margin: 10px 200px 10px 200px;">
  <h4> <%= post.title %> </h4>
  <p class="form-comment" > Created at <%= post.date %> </p>
  <p class="form-comment" > Autor: <%= "#{post.user.first_name} #{post.user.last_name}" %> </p>
  <p style = "text-align:left;"> <%= post.content %> </p>
  <br>
  <%= link_to "likes #{ post.likes.count }", likes_add_delete_path(post) %>
  <span style="color: #EE2412; font-size: 20px; font-family: 'Comic Sans MS';">&hearts;</span>
  <br>
  <% if current_user == post.user %>
    <%= link_to "edit |", edit_posts_path(post) %>

   <%= link_to "delete", posts_path(post), method: :delete,
                                   data: { confirm: "You sure?" } %>
  <% end %>
</div>
<%= render 'posts/comments', post: post %>
<% end %>
<br>

app/views/posts/edit.html.erb
<h3> Edit post:<br> <%= @post.title %></h3>
<%= form_for(@post, url: posts_path) do |f| %>

  <div class="field">
    <%= f.hidden_field :id   %>
    <%= f.label "Title"  %>
    <%= f.text_field :title , size: "60x"%>
    <br>
    <%= f.label "Content"  %>
    <br>
    <%= f.text_area :content, size: "60x12", placeholder: "Compose new post..." %><br>
  </div>
<%= f.submit "Update", class: "btn btn-primary" %>
<% end %>

app/views/posts/show.html.erb
<%= render 'posts/posts'  %>