config/routes.rb
Rails.application.routes.draw do

  resources :comments

  resource :posts

  resource :relationships, only: [:create, :destroy]

  resource :users, only: [:edit, :update] do
    member	do
      get :wish_frend, :del_wish_frend
      get :accept_frend, :not_accept_frend
    end
  end

  match 'post/id',  to: 'posts#show_id',    via: 'get', as: :post_show_id

  match 'likes',  to: 'likes#add_delete',    via: 'get', as: :likes_add_delete

  match 'users/show_new_friends',  to: 'users#show_new_friends',    via: 'get' , as: :show_users_new_friends
  match 'users/show_invites',  to: 'users#show_invites',    via: 'get' , as: :show_users_invites
  match 'users/show_wishes',  to: 'users#show_wishes',    via: 'get' , as: :show_users_wishes
  match 'users/show_friends',  to: 'users#show_friends',    via: 'get' , as: :show_users_friends

  match 'users/:id/show',  to: 'users#show',    via: 'get' , as: :show_users
  match 'users/index',  to: 'users#index',     via: 'get'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'welcome#index'

end

app/views/layouts/_header.html.erb
<header class = "navbar">
  <% if user_signed_in? %>
    <%= link_to "#{current_user.first_name} #{current_user.last_name}", root_path, id: "logo_name" %>
  <% end %>
  <div class="container">
    <%= link_to "My facebook", root_path, id: "logo" %>

    <nav>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
        <%= render 'layouts/log_in_navigate' %>
        <% else %>
        <%= render 'layouts/log_out_navigate' if @index %>
        <% end %>
      </ul>
    </nav>
  </div>
</heder>

app/views/layouts/_log_in.html.erb
<%= form_for(resource, as: resource_name, url: session_path(resource_name),  html: {class: 'form-inline'} ) do |f| %>
  <div class="form-login">
    <%= f.label :email, class: "log_label" %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="form-login">
    <%= f.label :password, class: "log_label" %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="form-login">
    <%= f.submit "Log in"%>
  </div>
<% end %>

app/views/layouts/_log_in_navigate.erb
        <li><%= link_to "Profile", "#" ,id: "menu" %></li>
        <li><%= link_to "Settings", "#" ,id: "menu" %></li>
        <li><%= link_to "Users", users_index_path ,id: "menu" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" id = "menu">
              Friends  </b>
            <% if @invites != 0 || @new_frends != 0 %>
              <split>New</split>
            <% end %>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Find Friends", users_index_path %></li>
              <li><%= link_to "My Friends: #{@frends} ", show_users_friends_path %>  </li>
              <% if @new_frends != 0 %>
              <li><%= link_to "New Friends: #{@new_frends}", show_users_new_friends_path, style: "color:red;" %> </li>
              <% end %>
              <li class="divider"></li>
              <li>
                <% if @wish_frends != 0 %>
                <%= link_to "My wish to be friends: #{@wish_frends} ", show_users_wishes_path %>
                <% end %>
                <% if @invites != 0 %>
                <li><%= link_to "Invites from users: #{@invites}", show_users_invites_path ,style: "color:red;" %> </li>
                <% end %>
              </li>
            </ul>
          </li>
      <li><%= link_to "Sign out",  destroy_user_session_path, method: "delete" ,id: "menu" %></li>

app/views/layouts/_log_in_navigate.html.erb
        <li><%= link_to "Profile", "#" ,id: "menu" %></li>
        <li><%= link_to "Posts", posts_path ,id: "menu" %></li>
        <li><%= link_to "Users", users_index_path ,id: "menu" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" id = "menu">
              Friends  </b>
            <% if @invites != 0 || @new_frends != 0 %>
              <split>New</split>
            <% end %>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Find Friends", users_index_path %></li>
              <li><%= link_to "My Friends: #{@frends} ", show_users_friends_path %>  </li>
              <% if @new_frends != 0 %>
              <li><%= link_to "New Friends: #{@new_frends}", show_users_new_friends_path, style: "color:red;" %> </li>
              <% end %>
              <li class="divider"></li>
              <li>
                <% if @wish_frends != 0 %>
                <%= link_to "My wish to be friends: #{@wish_frends} ", show_users_wishes_path %>
                <% end %>
                <% if @invites != 0 %>
                <li><%= link_to "Invites from users: #{@invites}", show_users_invites_path ,style: "color:red;" %> </li>
                <% end %>
              </li>
            </ul>
          </li>
      <li><%= link_to "Sign out",  destroy_user_session_path, method: "delete" ,id: "menu" %></li>

app/views/layouts/_log_out_navigate.html.erb
<%= form_for(resource, as: resource_name, url: session_path(resource_name),  html: {class: 'form-inline'} ) do |f| %>
  <div class="form-login">
    <%= f.label :email, class: "log_label" %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="form-login">
    <%= f.label :password, class: "log_label" %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="form-login">
    <%= f.submit "Log in"%>

  </div><br>
  <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
<% end %>

app/views/layouts/_profile.html.erb
<div style = "text-align : left; margin: 20px;">
  <h1><%= "#{current_user.first_name} #{current_user.last_name}" %></h1>
  <div>
  <%= image_tag current_user.avatar.url(:medium) %>
  </div>

  <br>
  <p><b>Gender: </b><%= current_user.gender %></p>
  <p><b>Location:</b> <%= current_user.location %></p>
  <p><b>Birthdate:</b> <%= current_user.birthday %></p>

  <p><%= link_to "Edit Profile", edit_users_path(current_user) %></p>
</div>

app/views/layouts/_sign_up.html.erb
<h1>Sign Up</h1>
  <h5> It's free and always will be. </h5>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <div class="field">
    <%= f.label :first_name, class: "sr-only" %><br />
    <%= f.text_field :first_name, autofocus: true, id: "inputEmail",
                                          class: " signin-field",  placeholder: "First name" %>
    <%= f.text_field :last_name, autofocus: true, id: "inputEmail",
                                          class: " signin-field",  placeholder: "Last name" %>
  </div>

  <div class="field">
    <%= f.label :email, class: "sr-only" %><br />
    <%= f.email_field :email, autofocus: true, id: "inputEmail",
                                          class: " signin-field-whide",  placeholder: "Email" %>
  </div>

  <div class="field">
    <%= f.label :password, class: "sr-only" %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off", id: "inputPassword",
                                          class: "signin-field-whide", placeholder: "Password" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation, class: "sr-only"  %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off", id: "inputPassword",
                              class: "signin-field-whide", placeholder: "Password confirmation" %>
  </div><br>

  <div class="actions">
    <%= f.submit "Sign up", class: "btn btn-lg btn-success" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyFacebook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <br>
  <br>
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
    <br>
    <br>
    <div class="senter">
      <%= yield %>
    </div>


</body>
</html>